#!/bin/bash
#
# Скрипт автоматической установки пакетов после свежей установки ОС Rosa Fresh
# Автор: Кастерин Юрий vk.com/yykast
#
echo "Установка пакетов из списка Package_list"
sed -n '/^#/!p' package_list | xargs urpmi --auto
#
echo "Удаление пакетов из списка Deleted"
#
sed -n '/^#/!p' deleted | xargs urpme --auto
#
echo "Проверка ОЗУ"
mem=$(grep -i "MemTotal" </proc/meminfo)
mem="${mem%[ ]*}"
mem="${mem##*[ ]}"
echo "$mem"
size="${mem[1]}"
#
echo "Проверка установки zram:"
#
ls /dev >/tmp/script.tmp
tmp=$(grep "zram" </tmp/script.tmp)
if [ -z "$tmp" ];
then
	echo "Zram НЕ установлен!!"
	if [[ "$size" -le 5242880 ]]
	then
		echo "Установка Zram"
		urpmi --force zramstart
		systemctl enable zram.service
		systemctl start zram.service
	else
		echo "Zram не требуется!!!"
	fi
else
	echo "Zram ЕСТЬ"
fi
rm -rf /tmp/script/tmp
echo "КОНЕЦ!!!"
exit 0
